version: "3"

services:
  postgres:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  frontend-challenge:
    depends_on:
      - "postgres"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: sensorbergberlin/frontend-challenge
    ports:
      - 4000:4000
